all: fetch

fetch:
	cp ~/git/protomodels/data/fake_stops3/index.html .
	cp ~/git/protomodels/data/fake_stops3/rawnumbers.html .
	cp ~/git/protomodels/data/fake_stops3/mass_hierarchy.png .
	cp ~/git/protomodels/data/fake_stops3/hiscore.slha .
	cp ~/git/protomodels/data/fake_stops3/pmodel.dict .
