all: fetch

fetch:
	cp ~/git/protomodels/data/rundir7/index.html .
	cp ~/git/protomodels/data/rundir7/rawnumbers.html .
	cp ~/git/protomodels/data/rundir7/mass_hierarchy.png .
	cp ~/git/protomodels/data/rundir7/hiscore.slha .
	cp ~/git/protomodels/data/rundir7/pmodel.dict .
