#Database address
[path]
databasePath = ../../smodels-database ; Give path to the database "text" directory or to the binary database file
slhaPath     = ../slha ; Give path to the folder containing the txname.tar files
smodelsPath  = ../../smodels
utilsPath    = ../../smodels-utils
#tarfiles = TSlepSlep_left.tar  ; (OPTIONAL) The name(s) of the tarfile(s). Must match the list in txnames.

#Select database analyses
[database]
# analyses = CMS-EXO-13-006 ;Set all to use all analyses included in the database
#to use only specific analyses, give a list of the names, e.g.
#analyses = CMS-PAS-SUS-13-008,CMS-SUS-13-013,ATLAS-CONF-2013-024,ATLAS-SUSY-2013-0
analyses = ATLAS-SUSY-2018-16
# analyses = CMS-SUS-16-033
txnames = TChiWZoff ; Set all to use all constraints included in the database
#txnames = T2
# dataselector = upperLimit 
dataselector = combined
#dataselector= all ; Allows to select specific data sets (signal regions) or dataType, e.g. upperLimit, efficiencyMap, data-cut0. combined means use results obtained from combining all signal regions.

[options]
# style = sabine ; Sabs style
prettyPlots = none ; If True it will produce pretty plots
generateData = False ; Set to True to run SModelS on the slha files. If False, use the already existing *.py files in the validation folder. If None or 'ondemand', produce data only if none are found.
# limitPoints = 10 ; Limit the number of probed model points, randomly chosen. If negative or left out, take all slha files.
#extraInfo = True ; put extra info on plot, like the time stamp, average time spent on model point, agreement factor, hostname
# model = nmssm ; the model to use (mssm,nmssm,default,idm)
ncpus = 1 ; the number of processes to start. Negative number means number of core plus that nunmber.
# axis = 2*[[x, (y, 1e-17)]] ; specify the axis, if not specified consult sms.root for the axes
ratioPlots = False ; plot also ratioplots, if possible. defaults to true
drawPaperPlot = True ; draw obs and exp plots with official, bestSR and combined(if present) exclusion lines on the same plot
createSModelSExclJson = True ; create SModelS Exclusion Json file, similar to official exclusion_jsons file

[drawPaperPlot]
drawBestSR = False
drawExpOfficialPM1 = True
drawObsOfficialPM1 = False
drawObsPM1 = False
max_y = auto
addlogo = False
# min_x = 100
sort_segments = False
show_points = True
# remove_segments = [[0,0],[205,10]]
# remove_segments = [[100,0],[115,90]]

#Specify k-factors, Allows to specify specific k-factors for each Txname
[kfactors]
#TChiChipmSlepStau = 1.25
#TChiChipmStauL = 1.25
#TChipChimSlepSnu = 1.25
#TChiChiSlepSlep = 1.25
