all: fetch

fetch:
	cp ~/git/protomodels/data/fake_ewkoff3/index.html .
	cp ~/git/protomodels/data/fake_ewkoff3/rawnumbers.html .
	cp ~/git/protomodels/data/fake_ewkoff3/mass_hierarchy.png .
	cp ~/git/protomodels/data/fake_ewkoff3/hiscore.slha .
	cp ~/git/protomodels/data/fake_ewkoff3/pmodel.dict .
