all: fetch

fetch:
	cp ~/git/protomodels/data/test2/index.html .
	cp ~/git/protomodels/data/test2/rawnumbers.html .
	cp ~/git/protomodels/data/test2/mass_hierarchy.png .
	cp ~/git/protomodels/data/test2/hiscore.slha .
	cp ~/git/protomodels/data/test2/pmodel.dict .
