all: fetch

fetch:
	cp ~/git/protomodels/data/fake_ewk2/index.html .
	cp ~/git/protomodels/data/fake_ewk2/rawnumbers.html .
	cp ~/git/protomodels/data/fake_ewk2/mass_hierarchy.png .
	cp ~/git/protomodels/data/fake_ewk2/hiscore.slha .
	cp ~/git/protomodels/data/fake_ewk2/pmodel.dict .
